---
abstract: 'filter data through an external process'
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
build_requires:
  Module::Build: 0.2808
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0
  perl: 5.006
  strict: 0
  warnings: 0
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IPC-Filter
provides:
  IPC::Filter:
    file: lib/IPC/Filter.pm
    version: 0.003
requires:
  Errno: 1.00
  Exporter: 0
  IO::Handle: 1.12
  IO::Poll: 0.01
  IPC::Open3: 1.01
  IPC::Signal: 1.00
  POSIX: 0
  Symbol: 0
  parent: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.003
