# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IPC-Filter
version:      0.000
version_from: lib/IPC/Filter.pm
installdirs:  site
requires:
    Errno:                         1.00
    IO::Handle:                    1.12
    IO::Poll:                      0.01
    IPC::Signal:                   1.00

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
